# Generated by Django 5.0.6 on 2024-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_me",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
