# Generated by Django 5.0.6 on 2024-05-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_about_me_alter_user_age_alter_user_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
    ]
